gameVersion=1.7.10
forgeVersion=10.13.4.1614
mappingType=mcp-snapshot
mcpVersion=20140925-1.7.10
javaVersion=8
useMixin=false
remapOutput=true
useAccessTransformer=false
useCoreMod=true
bridgeSlf4j=true
legacyLanguageFormat=true
excludeR8=org.scala-lang,com.mojang:patchy,net.minecraftforge:mergetool
excludeR8Jar=
