[versions]
fabric-loader = "0.16.13"
kotlin = "2.1.10"
loom = "1.10.1"
forge-gradle = "0.0.0"
kotlinpoet = "2.0.0"
coroutines = "1.10.1"
serialization = "1.8.0"
collections-immutable = "0.3.8"
parchmentmc-librarian-forgegradle = "1.+"
mixin-gradle = "0.7.+"
gr8 = "0.11.2"
koin = "4.0.2"
# DONT UPDATE IT BECAUSE JOML 1.10.5 IS USED WHEN MINECRAFT INTRODUCE JOML IN VERSION 1.19.3
#noinspection GradleDependency
joml = "1.10.5"
slf4j = "2.0.16"
# DONT UPDATE IT BECAUSE OLD MINECRAFT DEPENDS ON LOG4J 2.8.1
#noinspection GradleDependency
log4j = "2.8.1"
aboutlibraries = "11.5.0"
junit = "5.11.4"
voyager = "1.1.0-beta03"
asm = "9.7.1"
# DONT UPDATE IT BECAUSE MINECRAFT DEPENDS ON LWJGL
#noinspection GradleDependency
lwjgl = "3.1.0"
mod-dev-gradle = "2.0.93"
universal-tween-engine = "6.3.3"

# Android
agp = "8.7.3"
rust-android-gradle = "0.9.5"

# Publish
minotaur = "2.8.7"
maven-publish = "0.30.0"

# Compose
compose = "1.7.1"

[libraries]
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "serialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "collections-immutable" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koin" }
koin-logger-slf4j = { group = "io.insert-koin", name = "koin-logger-slf4j", version.ref = "koin" }
joml = { group = "org.joml", name = "joml", version.ref = "joml" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }
kotlin-test-junit5 = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5", version.ref = "kotlin" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "compose" }
compose-runtime-saveable = { group = "org.jetbrains.compose.runtime", name = "runtime-saveable", version.ref = "compose" }
voyager-navigator = { group = "cafe.adriel.voyager", name = "voyager-navigator", version.ref = "voyager" }
voyager-screenModel = { group = "cafe.adriel.voyager", name = "voyager-screenmodel", version.ref = "voyager" }
voyager-koin = { group = "cafe.adriel.voyager", name = "voyager-koin", version.ref = "voyager" }
asm = { group = "org.ow2.asm", name = "asm", version.ref = "asm" }
asm-commons = { group = "org.ow2.asm", name = "asm-commons", version.ref = "asm" }
lwjgl = { group = "org.lwjgl", name = "lwjgl", version.ref = "lwjgl" }
lwjgl-glfw = { group = "org.lwjgl", name = "lwjgl-glfw", version.ref = "lwjgl" }
universal-tween-engine = { group = "org.mini2Dx", name = "universal-tween-engine", version.ref = "universal-tween-engine" }

# BELOW ARE GRADLE PLUGINS
aboutlibraries-plugin = { group = "com.mikepenz.aboutlibraries.plugin", name = "com.mikepenz.aboutlibraries.plugin.gradle.plugin", version.ref = "aboutlibraries" }
gr8 = { group = "com.gradleup.gr8", name = "com.gradleup.gr8.gradle.plugin", version.ref = "gr8" }
fabric-loom = { group = "net.fabricmc", name = "fabric-loom", version.ref = "loom" }
forge-gradle = { group = "net.minecraftforge.gradle", name = "ForgeGradle", version.ref = "forge-gradle" }
parchmentmc-librarian-forgegradle = { group = "org.parchmentmc.librarian.forgegradle", name = "org.parchmentmc.librarian.forgegradle.gradle.plugin", version.ref = "parchmentmc-librarian-forgegradle" }
mixin-gradle = { group = "org.spongepowered.mixin", name = "org.spongepowered.mixin.gradle.plugin", version.ref = "mixin-gradle" }
modrinth-minotaur = { group = "com.modrinth.minotaur", name = "Minotaur", version.ref = "minotaur" }
mod-dev-gradle = { group = "net.neoforged.moddev", name = "net.neoforged.moddev.gradle.plugin", version.ref = "mod-dev-gradle" }

[plugins]
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# Android
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
rust-android-gradle = { id = "org.mozilla.rust-android-gradle.rust-android", version.ref = "rust-android-gradle" }
android-library = { id = "com.android.library", version.ref = "agp" }

# Publish
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }

# Compose
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }